### ISSUE TITLE
vbcc minimal impl ? where to start

### ISSUE THREAD

**Issue by Johnlon** [robinsonb5/EightThirtyTwo#2]
Did you find a ref for a minimal impl for a back end for vbcc or did you build yours from first principles OR strip back some existing one.

I'm building a back end for https://github.com/Johnlon/spam-1 but have only just started and reading the docs etc.

What's needed is a minimal back end end for a trivial model CPU with no optimisations and I was thinking of doing this along with a vid. Do you have anything useful?

Thanks John

**Comment by robinsonb5** [comment]
I just started with the "generic risc" backend which is part of the vbcc source tree - it's simple enough that there isn't much to strip back.  The backend documentation at http://www.ibaug.de/vbcc/doc/vbcc_13.html is also very good.

Feel free to email me at robinsonb5@gmail.com if you have any particular questions - and I've found Volker, VBCC's author, to be very helpful, too.

**Comment by Johnlon** [comment]
Thanks for your response.
Will defo need pointers.
I see a lot of use of ints in the code base where I'd have thought things
like an enum would help.
Makes it a bit more impenetrable.
I've gotten used to strongly statically types languages where complex code
lives.
